# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# Riff
windowrule = float on, match:class (^dev.diegovsky.Riff$), match:title (^riff$)
windowrule = size 1200 800, center on, match:class (^dev.diegovsky.Riff$)

# Kitty
windowrule = float on, match:class (^kitty$)
windowrule = size 1600 1000, center on, match:class (^kitty$)


windowrule {
  name = windowrule-1
  float = on
  size = 1600 1000
  move = 315 45
  match:title = ^(NETCAGE)$
}
