color0 #474747
color1 #ffb4ab
color2 #9ecaff
color3 #bbc7db
color4 #d6bee4
color5 #9ecaff
color6 #bbc7db
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #9ecaff
color11 #bbc7db
color12 #d6bee4
color13 #9ecaff
color14 #bbc7db
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #9ecaff
inactive_border_color #474747
url_color             #9ecaff

active_tab_foreground   #003258
active_tab_background   #9ecaff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
